import type { AICharacter, ContentItem, Book, SavedItem } from "./types";

export const CHARACTERS: AICharacter[] = [
  {
    id: "newton",
    name: "Isaac Newton",
    era: "1643–1727",
    subjects: ["physics", "math"],
    initial: "N",
    color: "#A8C8FF",
  },
  {
    id: "einstein-cartoon",
    name: "Professor Einstein",
    era: "1879–1955",
    subjects: ["physics", "math"],
    initial: "E",
    color: "#FFD6A5",
  },
  {
    id: "einstein",
    name: "Albert Einstein",
    era: "1879–1955",
    subjects: ["physics"],
    initial: "E",
    color: "#D4C4F0",
  },
  {
    id: "sunny",
    name: "Sunny & Jo",
    era: "Funland",
    subjects: ["biology", "history"],
    initial: "S",
    color: "#B8E8D0",
  },
];

/** Personality-only feed — illustration / 3D / realistic AI teacher portraits */
export const FEED_ITEMS: ContentItem[] = [
  {
    id: "c1",
    title: "Laws of Motion — why you fly forward in a car crash",
    sourceUrl: "https://tiktok.com/@physicsreal/video/1",
    platform: "tiktok",
    transcript:
      "Newton's first law: an object in motion stays in motion unless acted upon by an external force. In a car crash, the car stops suddenly but your body wants to keep moving — that's why seatbelts exist.",
    topics: ["physics"],
    qualityScore: 0.94,
    gradeLevel: "9-12",
    character: CHARACTERS[0],
    thumbnailColor: "#E4EEFF",
    posterUrl: "/media/newton-ai-talking.png",
    talkingPortrait: true,
    portraitStyle: "realistic",
    durationSec: 78,
    viewCount: 2_400_000,
  },
  {
    id: "c2",
    title: "E = mc² — why energy and mass are the same thing",
    sourceUrl: "https://tiktok.com/@einsteinreal/video/2",
    platform: "tiktok",
    transcript:
      "Mass is concentrated energy. When uranium splits, a tiny bit of mass converts to an enormous burst of energy — that's the idea behind E equals mc squared.",
    topics: ["physics"],
    qualityScore: 0.96,
    gradeLevel: "college",
    character: CHARACTERS[2],
    thumbnailColor: "#EDE4FF",
    posterUrl: "/media/einstein-realistic.png",
    talkingPortrait: true,
    portraitStyle: "realistic",
    durationSec: 92,
    viewCount: 5_100_000,
  },
  {
    id: "c3",
    title: "Can you pass this IQ test? — logic puzzles explained",
    sourceUrl: "https://instagram.com/p/einstein-cartoon-1",
    platform: "instagram",
    transcript:
      "Logic puzzles train your brain to spot patterns. Start with what you know for certain, eliminate what's impossible, and the answer reveals itself — just like solving equations on a chalkboard.",
    topics: ["math", "philosophy"],
    qualityScore: 0.91,
    gradeLevel: "9-12",
    character: CHARACTERS[1],
    thumbnailColor: "#FFE5D4",
    posterUrl: "/media/einstein-cartoon.png",
    talkingPortrait: true,
    portraitStyle: "illustration",
    durationSec: 64,
    viewCount: 3_700_000,
  },
  {
    id: "c4",
    title: "Green means go! — crossing the street safely",
    sourceUrl: "https://tiktok.com/@jojofunland/video/4",
    platform: "tiktok",
    transcript:
      "Green means right. Yellow says get ready, slow. Look both ways then off we go round the corner! Always stop, look, and listen before you cross.",
    topics: ["biology"],
    qualityScore: 0.88,
    gradeLevel: "K-5",
    character: CHARACTERS[3],
    thumbnailColor: "#DFF5EC",
    posterUrl: "/media/sunny-kids-3d.png",
    talkingPortrait: true,
    portraitStyle: "3d",
    durationSec: 48,
    viewCount: 1_900_000,
  },
];

export const MOCK_BOOKS: Book[] = [
  {
    id: "b1",
    title: "Physics Essentials",
    items: [],
    coverColor: "#E4EEFF",
    gradeLevel: "9-12",
  },
  {
    id: "b2",
    title: "World History",
    items: [],
    coverColor: "#DFF5EC",
    gradeLevel: "college",
  },
  {
    id: "b3",
    title: "Calculus Concepts",
    items: [],
    coverColor: "#EDE4FF",
    gradeLevel: "9-12",
  },
];

export const MOCK_SAVED: SavedItem[] = [
  {
    id: "s1",
    contentId: "c1",
    title: "Laws of Motion",
    topic: "physics",
    savedAt: new Date("2026-06-05"),
    notes: "F = ma is the short form",
    bookId: "b1",
  },
  {
    id: "s2",
    contentId: "c2",
    title: "E = mc²",
    topic: "physics",
    savedAt: new Date("2026-06-04"),
    notes: "Review before midterm",
    bookId: "b3",
  },
  {
    id: "s3",
    contentId: "c3",
    title: "IQ Logic Puzzles",
    topic: "math",
    savedAt: new Date("2026-06-03"),
    notes: "",
    bookId: "b2",
  },
];
